# coding: utf-8

"""

    This is the API for the Pet Store.  # noqa: E501

    OpenAPI spec version: 1.0.0-rev1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreatePetRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'species': 'str'
    }

    attribute_map = {
        'name': 'name',
        'species': 'species'
    }

    def __init__(self, name=None, species=None):  # noqa: E501
        """CreatePetRequest - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._species = None
        self.discriminator = None
        self.name = name
        self.species = species

    @property
    def name(self):
        """Gets the name of this CreatePetRequest.  # noqa: E501

        The name of the pet, can be updated later  # noqa: E501

        :return: The name of this CreatePetRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreatePetRequest.

        The name of the pet, can be updated later  # noqa: E501

        :param name: The name of this CreatePetRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def species(self):
        """Gets the species of this CreatePetRequest.  # noqa: E501

        The species of the pet  # noqa: E501

        :return: The species of this CreatePetRequest.  # noqa: E501
        :rtype: str
        """
        return self._species

    @species.setter
    def species(self, species):
        """Sets the species of this CreatePetRequest.

        The species of the pet  # noqa: E501

        :param species: The species of this CreatePetRequest.  # noqa: E501
        :type: str
        """
        if species is None:
            raise ValueError("Invalid value for `species`, must not be `None`")  # noqa: E501

        self._species = species

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreatePetRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreatePetRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
