# coding: utf-8

"""

    This is the API for the Pet Store.  # noqa: E501

    OpenAPI spec version: 1.0.0-rev1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_pet_request import UpdatePetRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdatePetRequest(unittest.TestCase):
    """UpdatePetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdatePetRequest(self):
        """Test UpdatePetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_pet_request.UpdatePetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
