# coding: utf-8

"""

    This is the API for the Pet Store.  # noqa: E501

    OpenAPI spec version: 1.0.0-rev1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.read_api import ReadApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReadApi(unittest.TestCase):
    """ReadApi unit test stubs"""

    def setUp(self):
        self.api = ReadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_pet(self):
        """Test case for get_pet

        """
        pass

    def test_list_pets(self):
        """Test case for list_pets

        """
        pass


if __name__ == '__main__':
    unittest.main()
