# coding: utf-8

"""

    This is the API for the Pet Store.  # noqa: E501

    OpenAPI spec version: 1.0.0-rev1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.common_response_header import CommonResponseHeader  # noqa: E501
from swagger_client.rest import ApiException


class TestCommonResponseHeader(unittest.TestCase):
    """CommonResponseHeader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonResponseHeader(self):
        """Test CommonResponseHeader"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.common_response_header.CommonResponseHeader()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
