# coding: utf-8

"""

    This is the API for the Pet Store.  # noqa: E501

    OpenAPI spec version: 1.0.0-rev1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.write_api import WriteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWriteApi(unittest.TestCase):
    """WriteApi unit test stubs"""

    def setUp(self):
        self.api = WriteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_pet(self):
        """Test case for create_pet

        """
        pass

    def test_update_pet(self):
        """Test case for update_pet

        """
        pass


if __name__ == '__main__':
    unittest.main()
